### ISSUE TITLE
Реализовать двухэтапную регистрацию

### ISSUE THREAD

**Issue by igorcoding** [tech-team/decider-backend#11]
На клиенте будет реализован обязательно после регистрации показ страницы для ввода персональных данных.
Чтобы это все заработало, в каждом юзере придется, я думаю, завести флаг типа registration_complete, который после именно регистрации (логин + пароль или первого захода через соц сеть) равен false

Затем последует запрос на редактирование данных (скажем, /user_edit), в котором ты проверишь registration_complete. Если он false - то ты в обязательном порядке требуешь присутствия username в запросе (заставим юзера придумать его) и проверяешь его на уникальность.
Если true - то это обычный edit профиля

В самом приложении необходимо также будет знать, закончилась регистрация или нет - чтобы открывать нужную активити (либо main, либо edit).

Соответственно, те юзеры, которые не закончили регистрацию, но ломятся за логином или токеном - отвечать что регистрация не окончена.

**Comment by Abashinos** [comment]
Не очень мне удобно будет по урлу для редактирования юзера "добивать регистрацию". Может, лучше довеском к запросу на, например, /login досылать нужные поля? Чтобы в случае, если все нужны поля присланы, я мог бы сразу залогинить и выдать токен?

**Comment by igorcoding** [comment]
Немножко нелогично делать это на login, потому что токен ты уже отдал на регистрации, а там он типо сменится уже - это будет усложнением логики по сохранению токена на клиенте.
Почему неудобно в edit?

**Comment by Abashinos** [comment]
Я просто не до конца понял видимо. У юзера уже будет токен, но не надо ему разрешать ломиться куда? Только на /login ? А что, если токен просрочится, как тогда юзеру дослать данные?

**Comment by igorcoding** [comment]
Не надо разрешаться ломиться на все урлы, кроме /edit (ну и естественно /login, /refresh), причем он обязан прислать username в нем.

Если токен просрочился - он по стандартной схеме идет на рефреш
