### ISSUE TITLE
Изменение подгрузки комментов

### ISSUE THREAD

**Issue by igorcoding** [tech-team/decider-backend#15]
на запрос /comments серв должен отдать последние `limit` комментов к этому вопросу (подчеркиваю, последние)
т.е. offset мы отсчитываем не сначала, а с конца

будем показывать последние `limit` комментов и кнопочку сверху - показать еще 30 и они подгрузятся вверх

поэтому надо еще, чтобы сервер отвечал каким-нить полем еще, типа remaining - для того, чтобы знать сколько еще комментов "выше" есть к этому вопросу.

**Comment by Abashinos** [comment]
этсамое
