### ISSUE TITLE
Конец для авторизации пушей

### ISSUE THREAD

**Issue by igorcoding** [tech-team/decider-backend#16]
Создать конец, например, POST /auth_push
параметры:
- `access_token` - наш аксес токен
- `token` - токен gcm

**Comment by Abashinos** [comment]
Здесь нужно в первый раз прислать instanceid по идее
Но я не уверен, что нам он нужон, так как у нас есть foreign key на юзера...

**Comment by Abashinos** [comment]
А, вспомнил. Я должен в первый раз instanceid через gcm проверить, чтобы ты мне шнягу не слал. во

**Comment by Abashinos** [comment]
А в последующих запросах нужно слать instanceid как уникальный идентификатор, по которому я буду обновлять reg_token
