### ISSUE TITLE
Редактирование профиля пользователя

### ISSUE THREAD

**Issue by Abashinos** [tech-team/decider-backend#5]
Обсудить

**Comment by Abashinos** [comment]
Переведешь на меня, когда опишем требования к этому таску

**Comment by igorcoding** [comment]
edit будет отправляться multipart запросом, также как question_create (из-за того, что там может быть картинка)

Поля примерно следующие:
- avatar (без preview)
- username - имя пользователя
- first_name 
- last_name
- gender ("N", "M", "F")
- birthday (в формате YYYY-MM-DD)
- country
- city
- about - небольшой текст, который юзер оставляет о себе (оставим пока, ибо надо занять чем-то место в интерфейсе, может потом уберем)

Если что - дополним или удалим поля.
